'use strict';
const bcrypt = require("bcryptjs");

let options = {};
if(process.env.NODE_ENV === 'production') {
  options.schema = process.env.SCHEMA; //define your schema in options object
}

module.exports = {
  up: async (queryInterface, Sequelize) => {
    options.tableName = "Spots";
    return queryInterface.bulkInsert(
      options,
      [
        {
          address:'123 A. Street Fairbanks, Alaska 99703',
          city: 'Fairbanks',
          state: 'Alaska',
          country: 'United States',
          lat: 64.8401,
          lng: -147.7200,
          name: 'River Rest',
          description:'Stunning mansion with 6 bedrooms and picturesque views of the Chena River.',
          price: 119.00,
          ownerId: 1,
        },
        {
          address:'234 B. Street Leavenworth, Washington 98826',
          city: 'Leavenworth',
          state: 'Washington',
          country: 'United States',
          lat: 47.5962,
          lng: -120.6615,
          name: 'Mountain Dream Escape',
          description:'Na-Mu Lodge offers a luxurious mansion with 20 bedrooms, each with private baths, nestled in the scenic mountains.',
          price: 1303.00,
          ownerId: 2,
        },
        {
          address:'345 C. Street Fire Island Pines, New York 11782',
          city: 'Fire Island Pines',
          state: 'New York',
          country: 'United States',
          lat: 40.6653,
          lng: -73.0693,
          name: 'The Legendary Pyramid House',
          description:'Iconic architectural masterpiece with 10 bedrooms and breathtaking views, offering unparalleled peace and privacy.',
          price: 1460.00,
          ownerId: 3,
        },
        {
          address:'456 D. Street Baton Rouge, Louisiana 70801',
          city: 'Baton Rouge',
          state: 'Louisiana',
          country: 'United States',
          lat: 30.4515,
          lng: -91.1871,
          name: 'Charming Acadian Style Mansion',
          description:'This beautifully appointed 15 bedroom/10 bath Acadian Style Cottage is located on a private street.',
          price: 43.00,
          ownerId: 4,
        },
        {
          address:'567 E. Street Albuquerque, New Mexico 87105',
          city: 'Albuquerque',
          state: 'New Mexico',
          country: 'United States',
          lat: 35.0844,
          lng: -106.6504,
          name: 'Oasis in the City',
          description:'Lovely 7 bd / 5 ba "casita" (guesthouse) nestled on an acre in the beautiful North Valley.',
          price: 110.00,
          ownerId: 5,
        },
        {
          address: '1234 W. Lane Los Angeles, California 90001',
          city: 'Los Angeles',
          state: 'California',
          country: 'United States',
          lat: 34.0522,
          lng: -118.2437,
          name: 'Urban Retreat',
          description: 'Charming 6 bd / 5 ba mansion located in the heart of downtown.',
          price: 150.00,
          ownerId: 6,
        },
        {
          address: '789 S. Avenue Miami, Florida 33130',
          city: 'Miami',
          state: 'Florida',
          country: 'United States',
          lat: 25.7617,
          lng: -80.1918,
          name: 'Tropical Paradise',
          description: 'Cozy 8 bd / 5 ba beachfront mansion with stunning ocean views.',
          price: 180.00,
          ownerId: 3,
        },
        {
          address: '456 N. Road Seattle, Washington 98101',
          city: 'Seattle',
          state: 'Washington',
          country: 'United States',
          lat: 47.6062,
          lng: -122.3321,
          name: 'Urban Oasis',
          description: 'Spacious 9 bd / 6 ba mansion in the vibrant downtown area.',
          price: 250.00,
          ownerId: 1,
        },
        {
          address: '789 E. Avenue Chicago, Illinois 60601',
          city: 'Chicago',
          state: 'Illinois',
          country: 'United States',
          lat: 41.8781,
          lng: -87.6298,
          name: 'City Chic Retreat',
          description: 'Modern 10 bd / 8 ba mansion in a trendy neighborhood with skyline views.',
          price: 200.00,
          ownerId: 4,
        },
        {
          address: '123 Main Street San Francisco, California 94101',
          city: 'San Francisco',
          state: 'California',
          country: 'United States',
          lat: 37.7749,
          lng: -122.4194,
          name: 'Cozy Urban Retreat',
          description: 'Quaint 5 bd / 3 ba mansion located in a charming neighborhood near downtown.',
          price: 120.00,
          ownerId: 2,
        },
        {
          address: '123 Oak Street New York, New York 10001',
          city: 'New York',
          state: 'New York',
          country: 'United States',
          lat: 40.7128,
          lng: -74.0060,
          name: 'Central Park Retreat',
          description: 'Spacious 12 bd / 9 ba house overlooking Central Park in the heart of New York City.',
          price: 300.00,
          ownerId: 4,
        },
        {
          address: '456 Pine Street San Francisco, California 94101',
          city: 'San Francisco',
          state: 'California',
          country: 'United States',
          lat: 37.7749,
          lng: -122.4194,
          name: 'Modern Mansion in SoMa',
          description: 'Contemporary 6 bd / 6 ba mansion located in the vibrant South of Market (SoMa) neighborhood.',
          price: 200.00,
          ownerId: 2,
        },
        {
          address: '789 Elm Street Miami, Florida 33130',
          city: 'Miami',
          state: 'Florida',
          country: 'United States',
          lat: 25.7617,
          lng: -80.1918,
          name: 'Oceanfront Paradise',
          description: 'Luxurious 8 bd / 6 ba beachfront mansion with stunning ocean views in Miami.',
          price: 450.00,
          ownerId: 3,
        },
        {
          address: '456 Oak Lane Austin, Texas 78701',
          city: 'Austin',
          state: 'Texas',
          country: 'United States',
          lat: 30.2672,
          lng: -97.7431,
          name: 'Hip Downtown Mansion',
          description: 'Trendy 6 bd / 5.5 ba mansion located in the vibrant downtown area of Austin.',
          price: 280.00,
          ownerId: 6,
        },
        {
          address: '789 Maple Avenue Seattle, Washington 98101',
          city: 'Seattle',
          state: 'Washington',
          country: 'United States',
          lat: 47.6062,
          lng: -122.3321,
          name: 'Seattle Skyline Retreat',
          description: 'Spacious 14 bd / 10 ba (1,800 sq ft) mansion with panoramic views of the Seattle skyline.',
          price: 380.00,
          ownerId: 1,
        },
        {
          address: '123 Pine Street Chicago, Illinois 60601',
          city: 'Chicago',
          state: 'Illinois',
          country: 'United States',
          lat: 41.8781,
          lng: -87.6298,
          name: 'Urban Chic',
          description: 'Charming 5 bd / 3 ba (700 sq ft) house in a vibrant neighborhood of downtown Chicago.',
          price: 180.00,
          ownerId: 5,
        },
        {
          address: '456 Elm Street Boston, Massachusetts 02101',
          city: 'Boston',
          state: 'Massachusetts',
          country: 'United States',
          lat: 42.3601,
          lng: -71.0589,
          name: 'Historic Brownstone Mansion',
          description: 'Elegant 9 bd / 7 ba (1,200 sq ft) mansion in a historic brownstone building in downtown Boston.',
          price: 320.00,
          ownerId: 5,
        },
        {
          address: '789 Oak Street San Diego, California 92101',
          city: 'San Diego',
          state: 'California',
          country: 'United States',
          lat: 32.7157,
          lng: -117.1611,
          name: 'Beachfront Bungalow',
          description: 'Fun 8 bd / 5 ba bungalow just steps away from the beautiful beaches of San Diego.',
          price: 250.00,
          ownerId: 6,
        },
        {
          address: '123 Main Street Denver, Colorado 80202',
          city: 'Denver',
          state: 'Colorado',
          country: 'United States',
          lat: 39.7392,
          lng: -104.9903,
          name: 'Mountain View Mansion',
          description: 'Cozy 8 bd / 8 ba mansion with breathtaking mountain views in the outskirts of Denver.',
          price: 200.00,
          ownerId: 2,
        },
        {
          address: '456 Elm Street New Orleans, Louisiana 70112',
          city: 'New Orleans',
          state: 'Louisiana',
          country: 'United States',
          lat: 29.9511,
          lng: -90.0715,
          name: 'French Quarter Oasis',
          description: 'Charming 15 bd / 12 ba mansion located in the historic French Quarter of New Orleans.',
          price: 180.00,
          ownerId: 4,
        },
        {
          address: '789 Maple Avenue Nashville, Tennessee 37201',
          city: 'Nashville',
          state: 'Tennessee',
          country: 'United States',
          lat: 36.1627,
          lng: -86.7816,
          name: 'Music City Retreat',
          description: 'Spacious 5 bd / 4 ba home located in the vibrant city of Nashville, the heart of country music.',
          price: 350.00,
          ownerId: 6,
        },
        {
          address: '123 Oak Street Honolulu, Hawaii 96813',
          city: 'Honolulu',
          state: 'Hawaii',
          country: 'United States',
          lat: 21.3069,
          lng: -157.8583,
          name: 'Tropical Paradise Villa',
          description: 'Exquisite 8 bd / 7 ba villa with lush gardens and stunning ocean views in Honolulu.',
          price: 650.00,
          ownerId: 1,
        },
        {
          address: '456 Pine Street Portland, Oregon 97204',
          city: 'Portland',
          state: 'Oregon',
          country: 'United States',
          lat: 45.5122,
          lng: -122.6587,
          name: 'Modern Mansion in the Pearl District',
          description: 'Stylish 9 bd / 8 ba mansion located in the trendy Pearl District of Portland.',
          price: 220.00,
          ownerId: 3,
        },
      ],
      {}
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete(options, {}, {});
  }

}

// options.tableName = 'Spots';

// const { Spot, User } = require('../models');

// const spots = [
//   {
//     address:'123 A. Street Fairbanks, Alaska 99703',
//     city: 'Fairbanks',
//     state: 'Alaska',
//     country: 'United States',
//     lat: 64.8401,
//     lng: -147.7200,
//     name: 'River Rest 1',
//     description:'Modern tiny home on the banks of the Chena River.',
//     price: 119.00,
//     ownerId: 1,
//   },
//   {
//     address:'234 B. Street Leavenworth, Washington 98826',
//     city: 'Leavenworth',
//     state: 'Washington',
//     country: 'United States',
//     lat: 47.5962,
//     lng: -120.6615,
//     name: 'Mountain Dream Escape',
//     description:'Na-Mu Lodge offers 4 luxurious suites each w/private baths, plus our bunk room w/plenty of space for everyone.',
//     price: 1303.00,
//     ownerId: 2,
//   },
//   {
//     address:'345 C. Street Fire Island Pines, New York 11782',
//     city: 'Fire Island Pines',
//     state: 'New York',
//     country: 'United States',
//     lat: 40.6653,
//     lng: -73.0693,
//     name: 'The Legendary Pyramid House',
//     description:'Iconic architectural masterpiece (b. 1961) with spectacular views offers unparalleled peace and privacy.',
//     price: 1460.00,
//     ownerId: 3,
//   },
//   {
//     address:'456 D. Street Baton Rouge, Louisiana 70801',
//     city: 'Baton Rouge',
//     state: 'Louisiana',
//     country: 'United States',
//     lat: 30.4515,
//     lng: -91.1871,
//     name: 'Charming Acadian Style Cottage',
//     description:'This beautifully appointed 1 bedroom/1 bath Acadian Style Cottage is located on a private street',
//     price: 43.00,
//     ownerId: 4,
//   },
//   {
//     address:'567 E. Street Albuquerque, New Mexico 87105',
//     city: 'Albuquerque',
//     state: 'New Mexico',
//     country: 'United States',
//     lat: 35.0844,
//     lng: -106.6504,
//     name: 'Oasis in the City',
//     description:'Lovely 1 bd / 1 ba (1,100 sq ft) "casita" (guesthouse) nestled on an acre in the beautiful North Valley.',
//     price: 110.00,
//     ownerId: 5,
//   },
// ];

// /** @type {import('sequelize-cli').Migration} */
// module.exports = {
//   async up (queryInterface, Sequelize) {
//     await Spot.bulkCreate(options, { validate: true });
//   },
// };
